language: generic
sudo: required
services:
    - docker

before_install:
    - docker build -t anandsivaji/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true anandsivaji/react-test npm run test -- --coverage
    
after_success:
    - docker build -t anandsivaji/multi-docker-client ./client
    - docker build -t anandsivaji/multi-docker-ngnix ./ngnix
    - docker build -t anandsivaji/multi-docker-server ./server
    - docker build -t anandsivaji/multi-docker-worker ./worker
    
    # Log in to the docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

    # Take these images to the docker hub
    - docker push anandsivaji/multi-docker-client
    - docker push anandsivaji/multi-docker-ngnix
    - docker push anandsivaji/multi-docker-server
    - docker push' anandsivaji/multi-docker-worker

