language: generic
sudo: required
services:
    - docker

before_install:
    - docker build -t anandsivaji/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true anandsivaji/react-test npm run test -- --coverage
    
after_success:
    - docker build -t anandsivaji/multi-client ./client
    - docker build -t anandsivaji/multi-nginx ./nginx
    - docker build -t anandsivaji/multi-server ./server
    - docker build -t anandsivaji/multi-worker ./worker
    
    # Log in to the docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

    # Take these images to the docker hub
    - docker push anandsivaji/multi-client
    - docker push anandsivaji/multi-nginx
    - docker push anandsivaji/multi-server
    - docker push anandsivaji/multi-worker

deploy:
    provider: elaticbeanstalk
    region: us-east-1
    app: multi-docker
    env: MultiDocker-env
    bucker_name: elasticbeanstalk-us-east-1-574322318218
    bucket_path: multi-docker
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY

