language: generic
sudo: required
services:
    - docker

before_install:
    - docker build -t anandsivaji/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true anandsivaji/react-test npm run test -- --coverage
    
after_success:
    - docker build -t anandsivaji/multi-docker-client ./client
    - docker build -t anandsivaji/multi-docker-ngnix ./ngnix
    - docker build -t anandsivaji/multi-docker-server ./server
    - docker build -t anandsivaji/multi-docker-worker ./worker
    # Take these images to the docker hub
    
